export function equivalente(key) {
    const colunas = {
        'acendedor': 'Acendedor',
        'alarme':'Alarme',
        'antena':'Antena',
        'arCondicionado':'Ar Condicionado',
        'bancos_encosto':'Bancos e Encostos',
        'buzina':'Buzina',
        'chave_roda':'Chave de Roda',
        'cinto_seguranca':'Cinto de Segurança',
        'desembacador':'Desembaçador',
        'embreagem':'Embreagem',
        'extindor_incendio':'Extintor de Incêndio',
        'farol_alto':'Farol Alto',
        'farol_baixo':'Farol Baixo',
        'farol_minimo':'Farol Mínimo',
        'fechamento_janelas':'Fechamento das Janelas',
        'freios_maos':'Freios de Mão',
        'freios_pe':'Freios de Pé',
        'giroflex':'Giroflex',
        'gps':'GPS',
        'lataria':'Lataria',
        'limp_p_brisa_tras': 'Limpador parabrisa traseiro',
        'limp_p_brisa_diant': 'Limpador parabrisa dianteiro' ,
        'luz_placa':'Luz da Placa',
        'luz_freio':'Luz do Freio',
        'luz_re':'Luz da Ré',
        'luz_interna':'Luz Interna',
        'luzes_painel':'Luzes do Painel',
        'macaco':'Macaco',
        'nv_agua_radiador':'Nível da Água do Radiador',
        'nv_oleo_freio':'Nível do Óleo do Freio',
        'nv_oleo_motor':'Nível do Óleo do Motor',
        'odometro':'Odômetro',
        'para_brisa':'Para-Brisa',
        'para_choq_diant':'Para-Choque Dianteiro',
        'para_choq_tras':'Para-Choque Traseiro',
        'pedais':'Pedais',
        'piscas_alerta':'Pisca Alerta',
        'estepe':'Estepe',
        'estado_pneus':'Estados dos Pneus',
        'portas_travas':'Portas-Travas',
        'quebra_sol':'Quebra-Sol',
        'radio':'Rádio',
        'retrovisor_diant':'Retrovisor Direito',
        'retrovisor_tras':'Retrovisor Esquerdo',
        'retrovisor_interno':'Retrovidor Interno',
        'seta_direita':'Seta Direita',
        'seta_esquerda':'Seta Esquerda',
        'sirene':'Sirene',
        'tapetes':'Tapetes',
        'triangulo_sinal':'Triângulo de Sinalização',
        'velocimetro':'Velocímetro',
        'ventilador':'Ventilador',
        'vidro_janelas':'Vidro das Janelas'
    }
  
    if (colunas[key])
      return colunas[key]
  
    return 'Chave inválida'
  }

  export function equivalenteMoto(key) {
    const colunas = {
        'afogador': 'Afogador',
        'amortecedores':'Amortecedores',
        'aparador_linha':'Aparador de Linha',
        'banco':'Banco',
        'bateria':'Bateria',
        'bau':'Baú',
        'buzina':'Buzina',
        'cabo_embreagem':'Cabo da Embreagem',
        'cabo_vela':'Cabo da Vela',
        'cabo_acelerador':'Cabo do Acelerador',
        'cabo_velocimetro':'Cabo do Velocímetro',
        'cabos_freios':'Cabo(s) do(s) Freio(s)',
        'calibragem_pneu':'Calibragem dos Pneus',
        'capa_moto':'Capa da Moto',
        'carenagens':'Carenagens',
        'cavalete_central':'Cavalete Central',
        'cavalete_lat':'Cavalete Lateral',
        'chave_geral_moto':'Chave Geral da Moto',
        'descarga':'Descarga',
        'disco_freio':'Disco de Freio',
        'embreagem': 'Embreagem',
        'espelhos_retrovisores': 'Espelhos Retrovisores' ,
        'estado_coroa':'Estado da Coroa',
        'estado_corrente':'Estado da Corrente',
        'estado_pinhao':'Estado do Pinhão',
        'farol_alto':'Farol Alto',
        'farol_baixo':'Farol Baixo',
        'fluidos_freios':'Flúidos de Freio',
        'giroflex':'Giroflex',
        'gps':'Gps',
        'interruptor_emerg':'Interruptor de Emergêngia',
        'interruptor_farol':'Interruptor do Farol',
        'interruptor_pisca':'Interruptor do Pisca',
        'jances':'Jances',
        'lanterna':'Lanterna',
        'lonas_freio':'Lonas do Freio',
        'luz_placa':'Luz da Placa',
        'luz_freio':'Luz do Freio',
        'luz_emergencia':'Luzes de Emergência',
        'luzes_painel':'Luzes do Painel',
        'luzes_estroboscopicas':'Luzes Estroboscópicas',
        'manete_embreagem':'Manete de Embreagem',
        'manete_freio':'Manete de Freio',
        'motor':'Motor',
        'nv_combustivel':'Nível do Combustível',
        'nv_fluido_bateria':'Nível de Flúido da Bateria',
        'nv_fluido_freio':'Nível de Flúido do Freio',
        'nv_liq_radiador':'Nível de Líquido no Radiador',
        'nv_oleo_motor':'Nível de Óleo do Motor',
        'nv_fluido_embreagem':'Nível do flúido da Embreagem',
        'partida_eletrica':'Partida Elétrica',
        'pastilhas_freio':'Pastilhas de Freio',
        'pedal_partida':'Pedal de Partida',
        'pedais_garupa':'Pedais do Garupa',
        'piscas':'Piscas',
        'pneus':'Pneus',
        'radiador':'Radiador',
        'sirene':'Sirene',
        'tambor_freio':'Tambor de Freio',
        'tampas':'Tampas',
        'tanque':'Tanque',
        'tensor_corrente':'Tensor de Corrente',
        'torneira_combustivel':'Torneira de Combustível',
        'varao_freio_tras':'Varão do Freio Traseiro',
        'vela':'Vela',
        'velocimetro':'Velocímetro'
    }
  
    if (colunas[key])
      return colunas[key]
  
    return 'Chave inválida'
  }

  